CONNECT sys AS SYSDBA;

CREATE PLUGGABLE DATABASE mon_27293_Semelane_MiningEquipmentMS_db
ADMIN USER mining_admin IDENTIFIED BY Semelane
FILE_NAME_CONVERT = (
    'C:\ORACLE\ORADATA\ORCL\PDBSEED\',
    'C:\ORACLE\ORADATA\ORCL\mon_27293_Semelane_MiningEquipmentMS_db\'
)
STORAGE (MAXSIZE 2G)
DEFAULT TABLESPACE users
    DATAFILE 'C:\ORACLE\ORADATA\ORCL\mon_27293_Semelane_MiningEquipmentMS_db\users01.dbf'
    SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE 500M
PATH_PREFIX = 'C:\ORACLE\ORADATA\ORCL\mon_27293_Semelane_MiningEquipmentMS_db\';

ALTER PLUGGABLE DATABASE mon_27293_Semelane_MiningEquipmentMS_db OPEN;
ALTER PLUGGABLE DATABASE mon_27293_Semelane_MiningEquipmentMS_db SAVE STATE;

SELECT name, open_mode FROM v$pdbs 
WHERE name = 'MON_27293_SEMELANE_MININGEQUIPMENTMS_DB';