ALTER SESSION SET CONTAINER = mon_27293_Semelane_MiningEquipmentMS_db;

-- Data Tablespace
CREATE TABLESPACE mining_data
DATAFILE 'C:\ORACLE\ORADATA\ORCL\mon_27293_Semelane_MiningEquipmentMS_db\mining_data01.dbf'
SIZE 200M AUTOEXTEND ON NEXT 20M MAXSIZE 1G
EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ONLINE;

-- Index Tablespace
CREATE TABLESPACE mining_indexes
DATAFILE 'C:\ORACLE\ORADATA\ORCL\mon_27293_Semelane_MiningEquipmentMS_db\mining_indexes01.dbf'
SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE 500M
EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ONLINE;

-- LOB Tablespace
CREATE TABLESPACE mining_lobs
DATAFILE 'C:\ORACLE\ORADATA\ORCL\mon_27293_Semelane_MiningEquipmentMS_db\mining_lobs01.dbf'
SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE 300M
EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ONLINE;

-- Temporary Tablespace
CREATE TEMPORARY TABLESPACE mining_temp
TEMPFILE 'C:\ORACLE\ORADATA\ORCL\mon_27293_Semelane_MiningEquipmentMS_db\mining_temp01.dbf'
SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE 500M
EXTENT MANAGEMENT LOCAL;

SELECT tablespace_name, status FROM dba_tablespaces 
WHERE tablespace_name LIKE 'MINING%';