ALTER SESSION SET CONTAINER = CDB$ROOT;

ALTER SYSTEM SET log_archive_dest_1 = 
    'LOCATION=C:\ORACLE\ORADATA\ORCL\archive' 
SCOPE=BOTH;

ALTER SESSION SET CONTAINER = mon_27293_Semelane_MiningEquipmentMS_db;
