-- BASIC RETRIEVAL QUERIES - SELECT *

-- Test 1.1: Retrieve all departments

SELECT * FROM DEPARTMENTS ORDER BY DEPARTMENT_ID;

-- Test 1.2: Retrieve all supervisors
SELECT * FROM SUPERVISORS ORDER BY SUPERVISOR_ID;

-- Test 1.3: Retrieve all equipment
SELECT * FROM EQUIPMENT ORDER BY EQUIPMENT_ID;

-- Test 1.4: Retrieve all operators
SELECT * FROM OPERATORS ORDER BY OPERATOR_ID;

-- Test 1.5: Retrieve all mining sites
SELECT * FROM MINING_SITES ORDER BY SITE_ID;

-- Test 1.6: Retrieve all shifts
SELECT * FROM SHIFTS ORDER BY SHIFT_ID;

-- Test 1.7: Retrieve all maintenance crew
SELECT * FROM MAINTENANCE_CREW ORDER BY CREW_ID;

-- Test 1.8: Retrieve all equipment assignments
SELECT * FROM EQUIPMENT_ASSIGNMENT ORDER BY ASSIGNMENT_ID;

-- Test 1.9: Retrieve all maintenance schedules
SELECT * FROM MAINTENANCE_SCHEDULE ORDER BY SCHEDULE_ID;

-- Test 1.10: Retrieve all maintenance history
SELECT * FROM MAINTENANCE_HISTORY ORDER BY HISTORY_ID;

-- Test 1.11: Retrieve all equipment usage logs
SELECT * FROM EQUIPMENT_USAGE_LOG ORDER BY USAGE_ID;

-- Test 1.12: Retrieve all downtime records
SELECT * FROM DOWNTIME_RECORDS ORDER BY DOWNTIME_ID;

-- Test 1.13: Retrieve all spare parts inventory
SELECT * FROM SPARE_PARTS_INVENTORY ORDER BY PART_ID;

-- Test 1.14: Retrieve all fuel consumption records
SELECT * FROM FUEL_CONSUMPTION ORDER BY CONSUMPTION_ID;

-- Test 1.15: Retrieve all public holidays
SELECT * FROM PUBLIC_HOLIDAYS ORDER BY HOLIDAY_DATE;

-- Test 1.16: Retrieve all audit logs
SELECT * FROM AUDIT_LOG ORDER BY AUDIT_ID;



-- Test 2.1: Equipment with Department Information (INNER JOIN)
SELECT 
    E.EQUIPMENT_ID,
    E.EQUIPMENT_TYPE,
    E.MODEL,
    E.SERIAL_NUMBER,
    E.STATUS,
    D.DEPARTMENT_NAME,
    D.LOCATION
FROM EQUIPMENT E
INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY E.EQUIPMENT_ID;

-- Test 2.2: Operators with Department and License Info (INNER JOIN)
SELECT 
    O.OPERATOR_ID,
    O.FIRST_NAME || ' ' || O.LAST_NAME AS OPERATOR_NAME,
    O.LICENSE_NUMBER,
    O.LICENSE_EXPIRY,
    O.STATUS,
    D.DEPARTMENT_NAME
FROM OPERATORS O
INNER JOIN DEPARTMENTS D ON O.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY O.OPERATOR_ID;

-- Test 2.3: Equipment Assignments with Full Details (MULTIPLE JOINS)
SELECT 
    EA.ASSIGNMENT_ID,
    E.EQUIPMENT_TYPE || ' - ' || E.MODEL AS EQUIPMENT,
    O.FIRST_NAME || ' ' || O.LAST_NAME AS OPERATOR,
    MS.SITE_NAME,
    S.SHIFT_NAME,
    EA.ASSIGNMENT_DATE,
    EA.STATUS
FROM EQUIPMENT_ASSIGNMENT EA
INNER JOIN EQUIPMENT E ON EA.EQUIPMENT_ID = E.EQUIPMENT_ID
INNER JOIN OPERATORS O ON EA.OPERATOR_ID = O.OPERATOR_ID
INNER JOIN MINING_SITES MS ON EA.SITE_ID = MS.SITE_ID
INNER JOIN SHIFTS S ON EA.SHIFT_ID = S.SHIFT_ID
ORDER BY EA.ASSIGNMENT_DATE DESC;

-- Test 2.4: Maintenance Schedule with Equipment and Crew (MULTIPLE JOINS)
SELECT 
    MS.SCHEDULE_ID,
    E.EQUIPMENT_TYPE || ' - ' || E.MODEL AS EQUIPMENT,
    E.SERIAL_NUMBER,
    MS.MAINTENANCE_TYPE,
    MS.SCHEDULED_DATE,
    MS.PRIORITY,
    MS.STATUS,
    MC.FIRST_NAME || ' ' || MC.LAST_NAME AS CREW_MEMBER
FROM MAINTENANCE_SCHEDULE MS
INNER JOIN EQUIPMENT E ON MS.EQUIPMENT_ID = E.EQUIPMENT_ID
LEFT JOIN MAINTENANCE_CREW MC ON MS.CREW_ID = MC.CREW_ID
ORDER BY MS.SCHEDULED_DATE DESC;

-- Test 2.5: Maintenance History with Complete Details (MULTIPLE JOINS)
SELECT 
    MH.HISTORY_ID,
    E.EQUIPMENT_TYPE || ' - ' || E.MODEL AS EQUIPMENT,
    MSC.MAINTENANCE_TYPE,
    MH.START_DATE,
    MH.END_DATE,
    MH.ACTUAL_DURATION_HOURS,
    TO_CHAR(MH.COST, '$999,999.00') AS COST,
    MC.FIRST_NAME || ' ' || MC.LAST_NAME AS PERFORMED_BY
FROM MAINTENANCE_HISTORY MH
INNER JOIN EQUIPMENT E ON MH.EQUIPMENT_ID = E.EQUIPMENT_ID
INNER JOIN MAINTENANCE_CREW MC ON MH.PERFORMED_BY = MC.CREW_ID
LEFT JOIN MAINTENANCE_SCHEDULE MSC ON MH.SCHEDULE_ID = MSC.SCHEDULE_ID
ORDER BY MH.START_DATE DESC;

-- Test 2.6: Equipment Usage with Operator and Site (MULTIPLE JOINS)
SELECT 
    EU.USAGE_ID,
    E.EQUIPMENT_TYPE || ' - ' || E.MODEL AS EQUIPMENT,
    O.FIRST_NAME || ' ' || O.LAST_NAME AS OPERATOR,
    MS.SITE_NAME,
    EU.LOG_DATE,
    EU.HOURS_OPERATED,
    EU.FUEL_CONSUMED_LITERS,
    EU.PRODUCTION_OUTPUT
FROM EQUIPMENT_USAGE_LOG EU
INNER JOIN EQUIPMENT E ON EU.EQUIPMENT_ID = E.EQUIPMENT_ID
INNER JOIN OPERATORS O ON EU.OPERATOR_ID = O.OPERATOR_ID
INNER JOIN MINING_SITES MS ON EU.SITE_ID = MS.SITE_ID
ORDER BY EU.LOG_DATE DESC;

-- Test 2.7: Downtime Records with Equipment and Reporter (MULTIPLE JOINS)
SELECT 
    DR.DOWNTIME_ID,
    E.EQUIPMENT_TYPE || ' - ' || E.MODEL AS EQUIPMENT,
    E.SERIAL_NUMBER,
    DR.DOWNTIME_TYPE,
    DR.START_TIME,
    DR.END_TIME,
    DR.DURATION_HOURS,
    TO_CHAR(DR.IMPACT_COST, '$999,999.00') AS IMPACT_COST,
    O.FIRST_NAME || ' ' || O.LAST_NAME AS REPORTED_BY
FROM DOWNTIME_RECORDS DR
INNER JOIN EQUIPMENT E ON DR.EQUIPMENT_ID = E.EQUIPMENT_ID
LEFT JOIN OPERATORS O ON DR.REPORTED_BY = O.OPERATOR_ID
ORDER BY DR.START_TIME DESC;

-- Test 2.8: Fuel Consumption with Equipment and Operator (MULTIPLE JOINS)
SELECT 
    FC.CONSUMPTION_ID,
    E.EQUIPMENT_TYPE || ' - ' || E.MODEL AS EQUIPMENT,
    FC.REFUEL_DATE,
    FC.LITERS_ADDED,
    TO_CHAR(FC.COST_PER_LITER, '$9.00') AS COST_PER_LITER,
    TO_CHAR(FC.TOTAL_COST, '$999,999.00') AS TOTAL_COST,
    O.FIRST_NAME || ' ' || O.LAST_NAME AS OPERATOR
FROM FUEL_CONSUMPTION FC
INNER JOIN EQUIPMENT E ON FC.EQUIPMENT_ID = E.EQUIPMENT_ID
LEFT JOIN OPERATORS O ON FC.OPERATOR_ID = O.OPERATOR_ID
ORDER BY FC.REFUEL_DATE DESC;

-- Test 2.9: Mining Sites with Supervisors (LEFT JOIN)
SELECT 
    MS.SITE_ID,
    MS.SITE_NAME,
    MS.LOCATION,
    MS.SITE_TYPE,
    MS.STATUS,
    S.FIRST_NAME || ' ' || S.LAST_NAME AS SUPERVISOR,
    S.PHONE AS SUPERVISOR_PHONE
FROM MINING_SITES MS
LEFT JOIN SUPERVISORS S ON MS.SUPERVISOR_ID = S.SUPERVISOR_ID
ORDER BY MS.SITE_ID;

-- Test 2.10: Departments with Manager Information (LEFT JOIN)
SELECT 
    D.DEPARTMENT_ID,
    D.DEPARTMENT_NAME,
    D.LOCATION,
    TO_CHAR(D.BUDGET, '$999,999,999.00') AS BUDGET,
    S.FIRST_NAME || ' ' || S.LAST_NAME AS MANAGER,
    S.EMAIL AS MANAGER_EMAIL
FROM DEPARTMENTS D
LEFT JOIN SUPERVISORS S ON D.MANAGER_ID = S.SUPERVISOR_ID
ORDER BY D.DEPARTMENT_ID;


-- Test 3.1: Equipment Count by Type
SELECT 
    EQUIPMENT_TYPE,
    COUNT(*) AS EQUIPMENT_COUNT,
    COUNT(CASE WHEN STATUS = 'Available' THEN 1 END) AS AVAILABLE,
    COUNT(CASE WHEN STATUS = 'In-Use' THEN 1 END) AS IN_USE,
    COUNT(CASE WHEN STATUS = 'Maintenance' THEN 1 END) AS IN_MAINTENANCE
FROM EQUIPMENT
GROUP BY EQUIPMENT_TYPE
ORDER BY EQUIPMENT_COUNT DESC;

-- Test 3.2: Equipment Count by Department
SELECT 
    D.DEPARTMENT_NAME,
    COUNT(E.EQUIPMENT_ID) AS EQUIPMENT_COUNT,
    COUNT(CASE WHEN E.STATUS = 'Available' THEN 1 END) AS AVAILABLE,
    COUNT(CASE WHEN E.STATUS = 'Maintenance' THEN 1 END) AS IN_MAINTENANCE
FROM DEPARTMENTS D
LEFT JOIN EQUIPMENT E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME
ORDER BY EQUIPMENT_COUNT DESC;

-- Test 3.3: Operators by Department and Status
SELECT 
    D.DEPARTMENT_NAME,
    O.STATUS,
    COUNT(*) AS OPERATOR_COUNT
FROM OPERATORS O
INNER JOIN DEPARTMENTS D ON O.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME, O.STATUS
ORDER BY D.DEPARTMENT_NAME, O.STATUS;

-- Test 3.4: Equipment Assignments by Date
SELECT 
    TO_CHAR(ASSIGNMENT_DATE, 'YYYY-MM-DD') AS ASSIGNMENT_DATE,
    COUNT(*) AS TOTAL_ASSIGNMENTS,
    COUNT(CASE WHEN STATUS = 'Completed' THEN 1 END) AS COMPLETED,
    COUNT(CASE WHEN STATUS = 'In-Progress' THEN 1 END) AS IN_PROGRESS,
    COUNT(CASE WHEN STATUS = 'Scheduled' THEN 1 END) AS SCHEDULED
FROM EQUIPMENT_ASSIGNMENT
GROUP BY TO_CHAR(ASSIGNMENT_DATE, 'YYYY-MM-DD')
ORDER BY ASSIGNMENT_DATE DESC;

-- Test 3.5: Maintenance Schedule by Type and Priority
SELECT 
    MAINTENANCE_TYPE,
    PRIORITY,
    COUNT(*) AS SCHEDULE_COUNT,
    ROUND(AVG(ESTIMATED_DURATION_HOURS), 2) AS AVG_DURATION_HOURS
FROM MAINTENANCE_SCHEDULE
GROUP BY MAINTENANCE_TYPE, PRIORITY
ORDER BY MAINTENANCE_TYPE, PRIORITY;

-- Test 3.6: Maintenance Costs by Equipment Type
SELECT 
    E.EQUIPMENT_TYPE,
    COUNT(MH.HISTORY_ID) AS MAINTENANCE_COUNT,
    TO_CHAR(SUM(MH.COST), '$999,999,999.00') AS TOTAL_COST,
    TO_CHAR(AVG(MH.COST), '$999,999.00') AS AVG_COST,
    ROUND(SUM(MH.ACTUAL_DURATION_HOURS), 2) AS TOTAL_HOURS
FROM MAINTENANCE_HISTORY MH
INNER JOIN EQUIPMENT E ON MH.EQUIPMENT_ID = E.EQUIPMENT_ID
GROUP BY E.EQUIPMENT_TYPE
ORDER BY SUM(MH.COST) DESC;

-- Test 3.7: Equipment Usage Statistics by Equipment
SELECT 
    E.EQUIPMENT_TYPE || ' - ' || E.MODEL AS EQUIPMENT,
    COUNT(EU.USAGE_ID) AS USAGE_RECORDS,
    ROUND(SUM(EU.HOURS_OPERATED), 2) AS TOTAL_HOURS,
    ROUND(AVG(EU.HOURS_OPERATED), 2) AS AVG_HOURS,
    ROUND(SUM(EU.FUEL_CONSUMED_LITERS), 2) AS TOTAL_FUEL_LITERS,
    ROUND(SUM(EU.PRODUCTION_OUTPUT), 2) AS TOTAL_PRODUCTION
FROM EQUIPMENT_USAGE_LOG EU
INNER JOIN EQUIPMENT E ON EU.EQUIPMENT_ID = E.EQUIPMENT_ID
GROUP BY E.EQUIPMENT_TYPE, E.MODEL
ORDER BY TOTAL_HOURS DESC;

-- Test 3.8: Downtime Analysis by Type
SELECT 
    DOWNTIME_TYPE,
    COUNT(*) AS INCIDENT_COUNT,
    ROUND(SUM(DURATION_HOURS), 2) AS TOTAL_HOURS,
    ROUND(AVG(DURATION_HOURS), 2) AS AVG_HOURS,
    TO_CHAR(SUM(IMPACT_COST), '$999,999,999.00') AS TOTAL_IMPACT_COST
FROM DOWNTIME_RECORDS
WHERE DURATION_HOURS IS NOT NULL
GROUP BY DOWNTIME_TYPE
ORDER BY SUM(DURATION_HOURS) DESC;

-- Test 3.9: Fuel Consumption by Equipment Type
SELECT 
    E.EQUIPMENT_TYPE,
    COUNT(FC.CONSUMPTION_ID) AS REFUEL_COUNT,
    ROUND(SUM(FC.LITERS_ADDED), 2) AS TOTAL_LITERS,
    ROUND(AVG(FC.LITERS_ADDED), 2) AS AVG_LITERS_PER_REFUEL,
    TO_CHAR(SUM(FC.TOTAL_COST), '$999,999,999.00') AS TOTAL_COST
FROM FUEL_CONSUMPTION FC
INNER JOIN EQUIPMENT E ON FC.EQUIPMENT_ID = E.EQUIPMENT_ID
GROUP BY E.EQUIPMENT_TYPE
ORDER BY SUM(FC.LITERS_ADDED) DESC;

-- Test 3.10: Spare Parts Inventory by Category
SELECT 
    CATEGORY,
    COUNT(*) AS PART_TYPES,
    SUM(QUANTITY_IN_STOCK) AS TOTAL_QUANTITY,
    TO_CHAR(SUM(QUANTITY_IN_STOCK * UNIT_COST), '$999,999,999.00') AS TOTAL_VALUE,
    COUNT(CASE WHEN QUANTITY_IN_STOCK < MINIMUM_STOCK_LEVEL THEN 1 END) AS LOW_STOCK_ITEMS
FROM SPARE_PARTS_INVENTORY
GROUP BY CATEGORY
ORDER BY SUM(QUANTITY_IN_STOCK * UNIT_COST) DESC;

-- Test 3.11: Monthly Fuel Consumption Trend
SELECT 
    TO_CHAR(REFUEL_DATE, 'YYYY-MM') AS MONTH,
    COUNT(*) AS REFUEL_COUNT,
    ROUND(SUM(LITERS_ADDED), 2) AS TOTAL_LITERS,
    TO_CHAR(SUM(TOTAL_COST), '$999,999.00') AS TOTAL_COST,
    ROUND(AVG(COST_PER_LITER), 2) AS AVG_COST_PER_LITER
FROM FUEL_CONSUMPTION
GROUP BY TO_CHAR(REFUEL_DATE, 'YYYY-MM')
ORDER BY MONTH DESC;

-- Test 3.12: Audit Log Activity by User
SELECT 
    USERNAME,
    COUNT(*) AS TOTAL_OPERATIONS,
    COUNT(CASE WHEN OPERATION = 'INSERT' THEN 1 END) AS INSERTS,
    COUNT(CASE WHEN OPERATION = 'UPDATE' THEN 1 END) AS UPDATES,
    COUNT(CASE WHEN OPERATION = 'DELETE' THEN 1 END) AS DELETES,
    COUNT(CASE WHEN STATUS = 'ALLOWED' THEN 1 END) AS ALLOWED,
    COUNT(CASE WHEN STATUS = 'DENIED' THEN 1 END) AS DENIED
FROM AUDIT_LOG
GROUP BY USERNAME
ORDER BY TOTAL_OPERATIONS DESC;


-- PART 4: SUBQUERIES 
-- Test 4.1: Equipment with Above Average Maintenance Costs
SELECT 
    E.EQUIPMENT_ID,
    E.EQUIPMENT_TYPE || ' - ' || E.MODEL AS EQUIPMENT,
    TO_CHAR(SUM(MH.COST), '$999,999.00') AS TOTAL_MAINT_COST
FROM EQUIPMENT E
INNER JOIN MAINTENANCE_HISTORY MH ON E.EQUIPMENT_ID = MH.EQUIPMENT_ID
GROUP BY E.EQUIPMENT_ID, E.EQUIPMENT_TYPE, E.MODEL
HAVING SUM(MH.COST) > (SELECT AVG(COST) FROM MAINTENANCE_HISTORY)
ORDER BY SUM(MH.COST) DESC;

-- Test 4.2: Operators Who Operated Most Equipment
SELECT 
    O.OPERATOR_ID,
    O.FIRST_NAME || ' ' || O.LAST_NAME AS OPERATOR_NAME,
    COUNT(DISTINCT EA.EQUIPMENT_ID) AS EQUIPMENT_COUNT
FROM OPERATORS O
INNER JOIN EQUIPMENT_ASSIGNMENT EA ON O.OPERATOR_ID = EA.OPERATOR_ID
GROUP BY O.OPERATOR_ID, O.FIRST_NAME, O.LAST_NAME
HAVING COUNT(DISTINCT EA.EQUIPMENT_ID) >= (
    SELECT AVG(EQUIP_COUNT)
    FROM (
        SELECT COUNT(DISTINCT EQUIPMENT_ID) AS EQUIP_COUNT
        FROM EQUIPMENT_ASSIGNMENT
        GROUP BY OPERATOR_ID
    )
)
ORDER BY EQUIPMENT_COUNT DESC;

-- Test 4.3: Equipment Downtime Summary
SELECT 
    EQUIPMENT_ID,
    ROUND(SUM(DURATION_HOURS), 2) AS TOTAL_DOWNTIME_HOURS,
    COUNT(*) AS DOWNTIME_INCIDENTS,
    ROUND(AVG(DURATION_HOURS), 2) AS AVG_INCIDENT_HOURS,
    MAX(DOWNTIME_TYPE) AS PRIMARY_DOWNTIME_TYPE
FROM DOWNTIME_RECORDS
WHERE DURATION_HOURS IS NOT NULL
GROUP BY EQUIPMENT_ID
ORDER BY SUM(DURATION_HOURS) DESC;

-- Test 4.4: Departments with Budget Above Average
SELECT 
    DEPARTMENT_NAME,
    TO_CHAR(BUDGET, '$999,999,999.00') AS BUDGET,
    (SELECT COUNT(*) FROM EQUIPMENT E WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID) AS EQUIPMENT_COUNT
FROM DEPARTMENTS D
WHERE BUDGET > (SELECT AVG(BUDGET) FROM DEPARTMENTS)
ORDER BY BUDGET DESC;

-- Test 4.5: Equipment Never Assigned
SELECT 
    E.EQUIPMENT_ID,
    E.EQUIPMENT_TYPE || ' - ' || E.MODEL AS EQUIPMENT,
    E.STATUS,
    E.PURCHASE_DATE
FROM EQUIPMENT E
WHERE NOT EXISTS (
    SELECT 1 
    FROM EQUIPMENT_ASSIGNMENT EA 
    WHERE EA.EQUIPMENT_ID = E.EQUIPMENT_ID
)
ORDER BY E.PURCHASE_DATE;

-- Test 4.6: Parts That Need Restocking
SELECT 
    PART_NUMBER,
    PART_NAME,
    CATEGORY,
    QUANTITY_IN_STOCK,
    MINIMUM_STOCK_LEVEL,
    (MINIMUM_STOCK_LEVEL - QUANTITY_IN_STOCK) AS SHORTAGE,
    TO_CHAR(UNIT_COST * (MINIMUM_STOCK_LEVEL - QUANTITY_IN_STOCK), '$999,999.00') AS RESTOCK_COST
FROM SPARE_PARTS_INVENTORY
WHERE QUANTITY_IN_STOCK < MINIMUM_STOCK_LEVEL
ORDER BY SHORTAGE DESC;

-- Test 4.7: Most Expensive Maintenance Jobs
SELECT 
    MH.HISTORY_ID,
    E.EQUIPMENT_TYPE || ' - ' || E.MODEL AS EQUIPMENT,
    TO_CHAR(MH.COST, '$999,999.00') AS COST,
    MH.ACTUAL_DURATION_HOURS,
    MC.FIRST_NAME || ' ' || MC.LAST_NAME AS PERFORMED_BY
FROM MAINTENANCE_HISTORY MH
INNER JOIN EQUIPMENT E ON MH.EQUIPMENT_ID = E.EQUIPMENT_ID
INNER JOIN MAINTENANCE_CREW MC ON MH.PERFORMED_BY = MC.CREW_ID
ORDER BY MH.COST DESC
FETCH FIRST 10 ROWS ONLY;

-- Test 4.8: Sites with Most Equipment Assignments
SELECT 
    MS.SITE_NAME,
    MS.LOCATION,
    (SELECT COUNT(*) 
     FROM EQUIPMENT_ASSIGNMENT EA 
     WHERE EA.SITE_ID = MS.SITE_ID) AS ASSIGNMENT_COUNT
FROM MINING_SITES MS
WHERE (SELECT COUNT(*) 
       FROM EQUIPMENT_ASSIGNMENT EA 
       WHERE EA.SITE_ID = MS.SITE_ID) > 0
ORDER BY ASSIGNMENT_COUNT DESC;

-- Test 4.9: Fuel Consumption by Operator
SELECT 
    OPERATOR_ID,
    ROUND(SUM(FUEL_CONSUMED_LITERS), 2) AS TOTAL_FUEL_LITERS,
    COUNT(*) AS USAGE_RECORDS,
    ROUND(AVG(FUEL_CONSUMED_LITERS), 2) AS AVG_FUEL_PER_USE
FROM EQUIPMENT_USAGE_LOG
WHERE FUEL_CONSUMED_LITERS IS NOT NULL
GROUP BY OPERATOR_ID
ORDER BY SUM(FUEL_CONSUMED_LITERS) DESC;

-- Test 4.10: Equipment with No Maintenance History
SELECT 
    E.EQUIPMENT_ID,
    E.EQUIPMENT_TYPE || ' - ' || E.MODEL AS EQUIPMENT,
    E.SERIAL_NUMBER,
    E.PURCHASE_DATE,
    E.STATUS
FROM EQUIPMENT E
WHERE NOT EXISTS (
    SELECT 1 
    FROM MAINTENANCE_HISTORY MH 
    WHERE MH.EQUIPMENT_ID = E.EQUIPMENT_ID
)
ORDER BY E.PURCHASE_DATE;

-- ============================================================================
-- BONUS QUERIES: Lookup Tables for IDs
-- ============================================================================

-- Bonus 4.11: Equipment Names for Downtime Records
SELECT 
    E.EQUIPMENT_ID,
    E.EQUIPMENT_TYPE || ' - ' || E.MODEL AS EQUIPMENT_NAME
FROM EQUIPMENT E
WHERE E.EQUIPMENT_ID IN (
    SELECT DISTINCT EQUIPMENT_ID 
    FROM DOWNTIME_RECORDS 
    WHERE DURATION_HOURS IS NOT NULL
)
ORDER BY E.EQUIPMENT_ID;

-- Bonus 4.12: Operator Names for Fuel Consumption
SELECT 
    O.OPERATOR_ID,
    O.FIRST_NAME || ' ' || O.LAST_NAME AS OPERATOR_NAME
FROM OPERATORS O
WHERE O.OPERATOR_ID IN (
    SELECT DISTINCT OPERATOR_ID 
    FROM EQUIPMENT_USAGE_LOG 
    WHERE FUEL_CONSUMED_LITERS IS NOT NULL
)
ORDER BY O.OPERATOR_ID;